version: '3'
services:
    front-proxy:
        build:
            context: .
            dockerfile: front-proxy/deploy/Dockerfile
        ports:
            - 9020:80
        networks:
            - envoymesh
    chat-api-server:
        build:
            context: .
            dockerfile: api-server/deploy/Dockerfile
        expose: 
            - "80"
        networks:
            - envoymesh
        volumes:
            - ./api-server/src:/app
    server:
        build:
            context: .
            dockerfile: server/deploy/Dockerfile
        restart: always
        expose:
            - "80"
        volumes:
            - ./server/src:/app
        networks:
            envoymesh:
                aliases:
                    - socket_server
        logging:
          options:
            max-size: 10m
            max-file: "5" 
    redis:
        image: redis:5.0-alpine
        expose:
            - "6379"
        networks:
            envoymesh:
                aliases:
                    - redis
        volumes:
          - /etc/timezone:/etc/timezone:ro
          - /etc/localtime:/etc/localtime:ro
        command: redis-server --appendonly no --maxmemory-policy allkeys-lru --maxmemory 1024mb --stop-writes-on-bgsave-error no
        logging:
          options:
            max-size: 10m
            max-file: "5"
    mongodb:
        image: mongo:4.0-xenial
        expose:
            - "27017"
        networks:
            envoymesh:
                aliases:
                    - db
        volumes:
          - /home/zoodfood/express-location-service/mongo/data:/data/db
          - /etc/timezone:/etc/timezone:ro
          - /etc/localtime:/etc/localtime:ro
        logging:
          options:
            max-size: 10m
            max-file: "5"

    client:
        build:
            context: .
            dockerfile: client/deploy/Dockerfile
        restart: always
        volumes:
            - ./client/src:/app
        networks:
            - envoymesh
        ports:
            - 8001:80
networks:
    envoymesh:
        driver: bridge

