version: '3'
services:
    server:
        build:
            context: .
            dockerfile: server/deploy/Dockerfile
        restart: always
        ports:
            - 8020:8020
            - 8081:8081
        volumes:
            - ./server/src:/app
        networks:
            - chat-app
    client:
        build:
            context: .
            dockerfile: client/deploy/Dockerfile
        restart: always
        volumes:
            - ./client/src:/app
        networks:
            - chat-app
        ports:
            - 8001:80
networks:
    chat-app:
        driver: bridge

